### PR TITLE
Update company logos on the homepage with similar dimensions, padding…

### PR DESCRIPTION
**Pull request by ocin-rye**
…, and format

### Public-Facing Changes

Removed padding, aligned the heights, and matched the format of company logo images.

### Description

To address the lack of consistent spacing for logo assets on MCAP websites.

### CODE REVIEW

**Comment by esthersweon** [comment]
@ocin-rye - The assets themselves look great, but we need to add styling to make these new logos show up correctly. 
I will take this PR over to implement.

What I see:
Screenshot 2023-12-11 at 1 29 17 PM
Screenshot 2023-12-11 at 1 29 23 PM

**Comment by ocin-rye** [comment]
> @ocin-rye - The assets themselves look great, but we need to add styling to make these new logos show up correctly. I will take this PR over to implement.
> 
> What I see: Screenshot 2023-12-11 at 1 29 17 PM Screenshot 2023-12-11 at 1 29 23 PM

Thanks! :pray: I'll change the assignee on linear to you.

**Review by esthersweon — CHANGES_REQUESTED** [review]
- Need updated Tangram logo (light mode) with correct fill areas
- Need updated Dexterity logo (smaller)

**Review by esthersweon — APPROVED** [review]
Added some padding, but looks great otherwise!

**Pull request merged**
