### PR TITLE
docs: build mcap.dev site with docusaurus

### PR DESCRIPTION
**Pull request by james-rms**
**Public-Facing Changes**

**Description**

### CODE REVIEW

**Comment by defunctzombie** [comment]
What's a good way to preview these docs?

**Comment by james-rms** [comment]
It looks like either:
1. stick with docusaurus v2 and use Vercel
2. Use docusaurus v1, which is apparently a "pure" static site generator, not a SPA

**Comment by james-rms** [comment]
If you just want to look at it now, clone, `cd docusaurus-docs && yarn install && yarn start`

**Comment by amacneil** [comment]
I tested the deployment at https://mcap-docs-preview-96cgxqbo7-foxglove.vercel.app/ , looks great.

Obviously still lots of content to figure out, but this feels like a really good navigation hierarchy (e.g. left and right navs), and it looks like you fixed the SPA URLs on the vercel deploy.

I'm feeling much better about this than readme.io, cleaner having all the doc generation in our own hands 👌 

I would suggest stripping the content down to a minimal "good" starting point, so we can focus on landing this first then make PRs to improve the content over time.

**Comment by james-rms** [comment]
Closing in favour of #518

**Comment by james-rms** [comment]
Closing in favour of #518

**Comment by james-rms** [comment]
Reopening for comparison with #518

**Pull request closed without merging**
