### PR TITLE
CLI: fieldToQualifiedMsgType handles fully qualified msg types

### PR DESCRIPTION
**Pull request by james-rms**
**Public-Facing Changes**
* Fixes a bug where the function converting a type reference in a `.msg` definition to a qualified type could not handle when a type reference was of the form `<packageName>/msg/<TypeName>`.

**Description**

### CODE REVIEW

**Comment by jtbandes** [comment]
Is that a valid .msg file? I thought the ROS codegen system didn’t accept this syntax last I looked.

**Comment by james-rms** [comment]
Not according to http://wiki.ros.org/msg or https://design.ros2.org/articles/legacy_interface_definition.html , but I have seen at least one definition file with this form in the wild.

**Review by jtbandes — CHANGES_REQUESTED** [review]
I tried building a ROS 2 message using this syntax, and it threw an `InvalidResourceName` error. I don't think this syntax is allowed so we probably shouldn't support it.

```
~/Desktop/ros2_ws$ colcon build
Starting >>> test_msgs
--- stderr: test_msgs                         
CMake Error at /opt/ros/galactic/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name test_msgs
  --arguments-file
  /home/parallels/Desktop/ros2_ws/build/test_msgs/rosidl_adapter__arguments__test_msgs.json
  --output-dir
  /home/parallels/Desktop/ros2_ws/build/test_msgs/rosidl_adapter/test_msgs
  --output-file
  /home/parallels/Desktop/ros2_ws/build/test_msgs/rosidl_adapter/test_msgs.idls)
  returned error code 1:

  Error processing 'test_msgs/msg/Colors colors' of 'test_msgs/Test':
  'test_msgs/msg/Colors'

  Traceback (most recent call last):

    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 516, in parse_message_string
      Type(type_string, context_package_name=pkg_name),
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 276, in __init__
      super(Type, self).__init__(
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 189, in __init__
      raise InvalidResourceName(type_string)

  rosidl_adapter.parser.InvalidResourceName: test_msgs/msg/Colors

Call Stack (most recent call first):
  /opt/ros/galactic/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:16 (rosidl_generate_interfaces)


make: *** [Makefile:1228: cmake_check_build_system] Error 1
---
Failed   <<< test_msgs [0.60s, exited with code 2]
                                
Summary: 0 packages finished [0.72s]
  1 package failed: test_msgs
  1 package had stderr output: test_msgs
```

**Comment by james-rms** [comment]
Makes sense, closing this PR.

**Pull request closed without merging**
