### PR TITLE
Spec: Consistent proto -> protobuf

### PR DESCRIPTION
**Pull request by amacneil**
So that the [schema encoding](https://github.com/foxglove/mcap/blob/main/docs/specification/well-known-schema-encodings.md) matches the [message encoding](https://github.com/foxglove/mcap/blob/main/docs/specification/well-known-message-encodings.md).

### CODE REVIEW

**Comment by defunctzombie** [comment]
/shrug - the idea was to support string schemas in addition to binary `FileDescriptorSet` in some future. The string schema files have the `.proto` extension: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto

**Comment by amacneil** [comment]
If we want to support both text and filedescriptorset, that's fine. Unclear if anyone has a need for that. But if we do, we should make it clear - calling one of them `proto` doesn't help.

**Review by jtbandes — APPROVED** [review]

**Comment by amacneil** [comment]
@defunctzombie @wkalt @jhurliman votes?

**Review by defunctzombie — APPROVED** [review]
protobuf is more namespaced than the more generic "proto" so 👍 from me

**Pull request merged**
