### PR TITLE
Fix issue where company logos become tiny on mobile device

### PR DESCRIPTION
**Pull request by esthersweon**
### Public-Facing Changes

- Fix issue where company logos become tiny on mobile device
- Add Dexterity logo

### CODE REVIEW

**Comment by jtbandes** [comment]
FYI will need to merge/rebase on https://github.com/foxglove/mcap/pull/1024

**Comment by jtbandes** [comment]
Issue doesn't really seem fixed:

image

**Comment by esthersweon** [comment]
@jtbandes - Let logos flex-wrap naturally, instead of enforcing 3 logos per row (with adequate spacing).

Screenshot 2023-11-21 at 1 16 13 PM

**Review by jtbandes — APPROVED** [review]
Looks better. I would say the logo sizes leave something to be desired – they have different visual weights due to the difference in fonts and such between the logos. We could compensate for this by adjusting their sizes (e.g. make the coco logo smaller since  its text is so large/bold, and make the tangram logo relatively larger)

**Comment by esthersweon** [comment]
@jtbandes - will follow up with making logos more consistent in size / spacing. cc: @2metres

**Pull request merged**
