### PR TITLE
Add flake8-import-order linter

### PR DESCRIPTION
**Pull request by emersonknapp**
The specific style is a matter of preference - but I like to have this linter plugged in for some consistency/readability improvement. Open to feedback on exact configuration.

No functional change in the diff, just formatting.

### CODE REVIEW

**Comment by emersonknapp** [comment]
Matter of personal taste - I don't agree, I find it easier to find and modify within a single alphabetic list, rather than thinking or caring whether I `import X` or `from X import ...` - however there is a setting that does it the way you're requesting and I'm happy in the end to do whatever as long as it's consistent. Maybe we need a third opinion?

**Comment by jtbandes** [comment]
Just to throw another idea out there — I've had good experiences using `black` as a formatter, which is highly opinionated and has very few configuration options.

**Comment by emersonknapp** [comment]
`black` is already enabled for this repo, but from what I understand it doesn't have opinions about import ordering. There is `isort` which has a `black` profile https://pycqa.github.io/isort/docs/configuration/black_compatibility.html. That seems an acceptable alternative - I'm seeing what that output looks like.

**Comment by emersonknapp** [comment]
Closing in favor of #914

**Pull request closed without merging**
