### PR TITLE
CLI: Omit metadata and attachment counts if stats are not present

### PR DESCRIPTION
**Pull request by wkalt**

### CODE REVIEW

**Review by jtbandes — APPROVED** [review]

**Comment by wkalt** [comment]
After this change,
```
$ mcap info tests/conformance/data/OneAttachment/OneAttachment.mcap
library: 
profile: 
channels:
```

We should probably apply similar logic to "channels", but that will require changing the library to return a pointer instead of a map, which will require a library release first.

**Comment by jtbandes** [comment]
We could also consider keeping the output lines but saying `attachments: unknown` explicitly instead of just omitting the line.

**Comment by wkalt** [comment]
yeah, I like that idea

**Comment by wkalt** [comment]
Updated output:
```
$ mcap info tests/conformance/data/OneAttachment/OneAttachment.mcap
library: 
profile: 
channels:
attachments: unknown
metadata: unknown
```

**Review by jtbandes — APPROVED** [review]

**Review by james-rms — APPROVED** [review]

**Pull request merged**
